### ISSUE TITLE
无法获取stoken

### ISSUE THREAD

**Issue by LiarOnce** [Womsxd/mihoyo_login#6]
扫码登录后报以下错误：
```
Traceback (most recent call last):
  File "C:\Users\LiarOnce\Desktop\mihoyo_login-st\qr_login.py", line 211, in <module>
    main()
  File "C:\Users\LiarOnce\Desktop\mihoyo_login-st\qr_login.py", line 205, in main
    uid, game_token = check_login(app_id, ticket, device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LiarOnce\Desktop\mihoyo_login-st\qr_login.py", line 148, in check_login
    if data["stat"] == "Init":
       ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by xuehantian** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by GamerNoTitle** [comment]
刚好发现获取不到，看到了这个issue
我来提供详细点的内容
通过对data进行print可以发现，data的内容如下
```json
{'stat': 'Init', 'payload': {'proto': 'Raw', 'raw': '', 'ext': ''}, 'realname_info': None}
```
看样子老米改了这一部分的返回
```
2024-07-18T20:02:52 INFO HTTP Request: POST https://hk4e-sdk.mihoyo.com/hk4e_cn/combo/panda/qrcode/query "HTTP/1.1 200 OK"
{'stat': 'Init', 'payload': {'proto': 'Raw', 'raw': '', 'ext': ''}, 'realname_info': None}
2024-07-18T20:02:52 INFO 等待扫码
2024-07-18T20:02:54 INFO HTTP Request: POST https://hk4e-sdk.mihoyo.com/hk4e_cn/combo/panda/qrcode/query "HTTP/1.1 200 OK"
None
Traceback (most recent call last):
  File "F:\Git\mihoyo_login\qr_login.py", line 212, in <module>
    main()
  File "F:\Git\mihoyo_login\qr_login.py", line 206, in main
    uid, game_token = check_login(app_id, ticket, device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Git\mihoyo_login\qr_login.py", line 149, in check_login
    if data["stat"] == "Init":
       ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by xuehantian** [comment]
我误打误撞好像解决了。在作者米游社签到项目下的issue里面我有提到怎么解决的，刚发不久。



---原始邮件---
发件人: "Pesy ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Womsxd/mihoyo_login] 无法获取stoken (Issue #6)




 
刚好发现获取不到，看到了这个issue
 我来提供详细点的内容
 通过对data进行print可以发现，data的内容如下
 {'stat': 'Init', 'payload': {'proto': 'Raw', 'raw': '', 'ext': ''}, 'realname_info': None}
 
看样子老米改了这一部分的返回
 2024-07-18T20:02:52 INFO HTTP Request: POST https://hk4e-sdk.mihoyo.com/hk4e_cn/combo/panda/qrcode/query "HTTP/1.1 200 OK" {'stat': 'Init', 'payload': {'proto': 'Raw', 'raw': '', 'ext': ''}, 'realname_info': None} 2024-07-18T20:02:52 INFO 等待扫码 2024-07-18T20:02:54 INFO HTTP Request: POST https://hk4e-sdk.mihoyo.com/hk4e_cn/combo/panda/qrcode/query "HTTP/1.1 200 OK" None Traceback (most recent call last):   File "F:\Git\mihoyo_login\qr_login.py", line 212, in <module&gt;     main()   File "F:\Git\mihoyo_login\qr_login.py", line 206, in main     uid, game_token = check_login(app_id, ticket, device)                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "F:\Git\mihoyo_login\qr_login.py", line 149, in check_login     if data["stat"] == "Init":        ~~~~^^^^^^^^ TypeError: 'NoneType' object is not subscriptable

**Comment by GamerNoTitle** [comment]
> 我误打误撞好像解决了。在作者米游社签到项目下的issue里面我有提到怎么解决的，刚发不久。

你是指那个项目嘛，我看到了你发的那个
但是我用的时候，不管我是用lsp模块（我手机有Lsposed）还是用lspatch打包后的那个，我都无法获取
可以详细地说一下是怎么操作的嘛

**Comment by GamerNoTitle** [comment]
我搞定了，但是我是root的手机开httpCanary抓包抓的

**Comment by EricsonXu114514** [comment]
> 我搞定了，但是我是root的手机开httpCanary抓包抓的

能展开讲讲手机怎么抓吗，我抓到三个但不知道哪个是需要的stoken，并且米游社还提示网络异常
![微信图片_20240725142221](https://github.com/user-attachments/assets/6b18d22b-6443-4fa7-be75-b83415955f0c)

**Comment by GamerNoTitle** [comment]
米游社网络异常就是你抓包软件的证书没有被手机信任，我手机是root了装了Magisk，然后打了个证书模块信任了抓包软件的证书才能抓的
抓了以后，找一个域名为`api-takumi.mihoyo.com`的请求里面，在cookie的值里面有`stoken=v2_xxxxxx`这个值就是了

**Comment by GamerNoTitle** [comment]
自制证书模块（把证书丢进包内的`/system/etc/security/cacerts`文件夹内再装），只是按照我的手机做的，变砖了别怪我，记得多备份
[HttpCanaryCertificateTrust.zip](https://github.com/user-attachments/files/16373075/HttpCanaryCertificateTrust.zip)

**Comment by xiaozhu52055** [comment]
#7 等待合并

**Comment by Womsxd** [comment]
> #7 等待合并

这并不是一个好的修复方案吧，估计崩铁更新后，也可能一块死了

**Comment by xiaozhu52055** [comment]
> > #7 等待合并
> 
> 这并不是一个好的修复方案吧，估计崩铁更新后，也可能一块死了

先用着，还不知道环境异常怎么搞

**Comment by nicklly** [comment]
> > #7 等待合并
> 
> 这并不是一个好的修复方案吧，估计崩铁更新后，也可能一块死了

有消息说改了扫码登陆方式 获取不了token了 好消息是api没变

**Comment by Container-Zero** [comment]
解决方案：https://github.com/Womsxd/MihoyoBBSTools/issues/180#issuecomment-2263315962

**Comment by qllokirin** [comment]
[    app_id = "1"](https://github.com/Womsxd/mihoyo_login/blob/11f2092725c3bf22941a82a6f3faf4dbde548b38/qr_login.py#L116)

我把这里改成2用未定事件簿登录就能用了 怪

**Comment by WcpXieG** [comment]
> [ app_id = "1"](https://github.com/Womsxd/mihoyo_login/blob/11f2092725c3bf22941a82a6f3faf4dbde548b38/qr_login.py#L116)
> 
> 我把这里改成2用未定事件簿登录就能用了 怪

真的欸，可以，也许老米未定没有改吧

**Comment by Seeridia** [comment]
> [ app_id = "1"](https://github.com/Womsxd/mihoyo_login/blob/11f2092725c3bf22941a82a6f3faf4dbde548b38/qr_login.py#L116)
> 
> 我把这里改成2用未定事件簿登录就能用了 怪

这个确实可以，要不叫 @Womsxd 直接改在源码里面吧

**Comment by nicklly** [comment]
你好，有事请
